services:
  - type: web
    name: calculadora-simbolica
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
